### PR TITLE
Add FuzzySortedDict

### PR DESCRIPTION
**Pull request by elihunter173**
This PR adds the class `FuzzySortedDict` from the already exists [FuzzySortedDict](https://github.com/ncsuarc/FuzzySortedDict) project I maintain. It allows for nearest-key lookup in a dictionary.

This has existed and been used continuously by my club for ~5 years as a quick and easy way to store and lookup data by timestamp. We previously maintained as its own tiny package, but I am interested in migrating it here to make it easier to find. Also, I just learned about this project seems like an excellent fit for what it is.

### CODE REVIEW

**Comment by grantjenks** [comment]
Took a quick look and I like it. I think it's worth including in sortedcollections.

I'm not sure about the name ``FuzzySortedDict``. Some alternatives:

* ``NearestDict``
* ``FuzzyDict``
* ``RoundingDict``
* ``ApproximateDict``

Can you explain more about the use case? Maybe that would help with naming.

**Comment by elihunter173** [comment]
Our main use case is we have services which deal with individual pieces of hardware on a UAV, like a gimbal (manages camera orientation). The service regularly queries the orientation of the gimbal and stores it in the fuzzy sorted dict. Meanwhile, the service is also listening for requests for gimbal orientation by timestamp. Whenever we take an image we make a request containing the timestamp of the image and the gimbal service returns the closest orientation data it has to that timestamp. It also occasionally cleans out old gimbal state to keep it's memory usage constant.

I've also used it in a few toy projects where I just want a weighted collection that doesn't change. Here I just take the weights of everything, normalize them, and then stuff them in a dict that rounds up using the cumsum of the previous weights and its weight. So if you had "foo" with a weight of 2 and "bar" with a weight of 1, the dict would be {2/3: "foo", 1: "bar"} and you can query using `random.random()`. I'm sure there are better tools for this particular use case, but for quick toy projects it works well enough.

As for the name, I agree the name is odd because it being sorted is irrelevant. I like `RoundingDict` or `FuzzyDict` the best of those. I think `ApproximateDict` is as good as rounding but a longer word and `NearestDict` doesn't seem to fit IMO with `ROUND_UP` and `ROUND_DOWN` being options.

**Comment by grantjenks** [comment]
Could you rebase against master? I have fixed the Python 3.4 issue in AppVeyor.

I also like "NearestDict" as the best name. I think the "rounding" term is misleading because of its numeric meaning. What if ROUND_UP became NEAREST_NEXT, ROUND_DOWN became NEAREST_PREV, and ROUND_CLOSEST became simply NEAREST?

**Comment by elihunter173** [comment]
I'm happy with NearestDict with those name changes. I just rebased to master and fixed the lint issues. Should be good to merge now if you don't have any other concerns.

While I was fixing the lint issues, I introduced a bug that the tests missed, so I also improved the tests a smidge.

**Comment by elihunter173** [comment]
@grantjenks Ping

**Comment by grantjenks** [comment]
Sorry this took me so long to merge! The code is great. It will go out today.

**Comment by grantjenks** [comment]
Released to PyPI in v2.1.0

**Pull request merged**
